### ISSUE TITLE
Migrate to using Helm V3, add helm upgrade support and publish Helm charts

### ISSUE THREAD

**Issue by pbelgundi** [pravega/zookeeper-operator#172]
## Description
This issue covers the following tasks :
- [x] Migrate to helm v3 and add self validating post-install and post-upgrade hooks (https://github.com/pravega/zookeeper-operator/issues/188)
- [x] Support helm upgrades (https://github.com/pravega/zookeeper-operator/issues/189)
- [x] Publish the helm charts to a public repository (https://github.com/pravega/zookeeper-operator/issues/190)

**Comment by fpj** [comment]
What needs to change in our charts to migrate to Helm 3? Asking differently, are our charts compatible with Helm 3 already?

The description of this issue is a bit short on detail....

**Comment by pbelgundi** [comment]
@fpj Our charts were written using helm 2. They have never been tested using helm3. Helm 3 could have some new features that could be useful. Primarily this issue is expected to cover:
1. Migration to Helm3
2. Making charts upgradable by having the right chart versions for each operator release.
3. Publishing charts to a repo.

**Comment by HoustonPutman** [comment]
For the last two items, the Solr Operator added scripts so that the helm chart can be easily built with the new version of the operator and be "published" very easily.

I'll link the PR in case the ZK operator wants to do something similar. There's been a few fixes since, but the bulk of the logic is there. https://github.com/bloomberg/solr-operator/pull/113

**Comment by SrishT** [comment]
@HoustonPutman thank you for the reference. Yes we are looking at doing something for our charts as well.

**Comment by SrishT** [comment]
Closing this issue as all 3 subtasks have been implemented.
